### ISSUE TITLE
Cannot identify checkmate

### ISSUE THREAD

**Issue by robertofalk** [bellerb/chess#2]
Hi,

there is an error in the checkmate validation, but I cannot really understand the code to fix it properly, but the error is here:

https://github.com/bellerb/chess/blob/main/chess.py#L321
```python
if k_pos[0] not in g_moves:
  if len(self.log) > 0 and self.log[-1][-1] is not '+':
      self.log[-1] += '+' #Check
  return [0, 0, 0]
```

I don't get why you check if `self.log[-1][-1] is not '+'`if this part of the code and some lines below are the only place that adds the '+' to the move. 

You can test with the following `EPD='4kb2/rpp1p3/6p1/6Np/3Q1B2/4P2b/PPP2PPP/RN1R2K1 w - -'`
The winning move is d4 d8.
Roberto

**Comment by bellerb** [comment]
Thanks for the heads up I'll try and fix the bug tomorrow. 

As for the:

```python:
if len(self.log) > 0 and self.log[-1][-1] is not '+':
    self.log[-1] += '+' #Check
````

The if statement is there to make sure I'm not adding in extra "+" when indicating it was a check. Without it, I was sometimes getting logs like:

ex. a4++++

**Comment by bellerb** [comment]
Okay, so I'm pretty sure this is fixed now. The problem seemed to be in the parsing of the blocked moves where I was not properly showing all good moves. Because of this, I changed 

```python:
#Parse all blocked moves
p_moves = [m for a in u_moves.values() for m in a]
g_moves = []
for m in u_moves:
    if m not in p_blocks:
        for a in u_moves[m]:
            if (a not in p_blocks) and a not in g_moves:
                g_moves.append(a)
            elif a in p_blocks:
               break
```

to 

```python:
#Parse all blocked moves
p_moves = [m for a in u_moves.values() for m in a]
g_moves = []
for m in u_moves:
    if m not in p_blocks:
        for a in u_moves[m]:
            if (a not in p_blocks) and a not in g_moves:
                g_moves.append(a)
```

This now correctly identifies the checkmate in EPD='4kb2/rpp1p3/6p1/6Np/3Q1B2/4P2b/PPP2PPP/RN1R2K1 w - -'
with the winning move is d4 d8.
